### PR TITLE
Pre training fixes

### LINKED ISSUE #22: Allow pointcloud to be loaded without displaying the subvolume regions
Currently the "Show subvolume regions" checkbox only works after a pointcloud has been loaded. This needs to work at the stage of pointcloud creation/loading so that a pointcloud can initially be loaded without the subvolumes shown.

### LINKED ISSUE #90: bulk run will generate the pointcloud even if a pointcloud has been loaded
Looking at the interface now, I believe a user would think the following is the expected behaviour: if the user loads a point cloud, the bulk run should run with that point cloud, just changing the number of points in a subvolume and its size.

Currently, the app will generate the point cloud with the parameters in the point cloud tab.

I suggest we add some separation:

1. Point Cloud Parameters
2. Generate Point cloud
3. Load Pointcloud (generated from the app or external)
3. display options

With 2 and 3 mutually exclusive.

image

### LINKED ISSUE #132: "Points in run" doesn't update automatically to total number in DVC run panel when new pointcloud is loaded

### PR DESCRIPTION
**Pull request by paskino**
* Makes a few GUI bugfixes, such as fix number of pointcloud displayed wrongly here and there. 
* Catches exceptions on load of files and opens message boxes
* Fix load of TIFF files
* On load of pointcloud display points only by default

closes #90 
closes #22 
closes #132

### CODE REVIEW

**Comment by paskino** [comment]
closes #22

**Comment by paskino** [comment]
closes #132

**Review by lauramurgatroyd — CHANGES_REQUESTED** [review]
Just tested and I found that:
#22 was not fixed - when I created a pointcloud, the subvolume regions were shown, and the "Display subvolume regions" checkbox was unticked.
I am getting this issue with tiff files: https://github.com/vais-ral/CILViewer/issues/310 - seems to be a closed issue in the viewer - what is happening here which is different?

Otherwise, I am happy with the changes to the way the bulk run works

**Comment by paskino** [comment]
You are right on #22 that it doesn't fix the display on creation, but #22 on the title refers to on load!

**Comment by lauramurgatroyd** [comment]
I only read the description, not the title, to me "load" (probably wrongly) means any time a pc is made

**Comment by paskino** [comment]
Mine was an excuse, clearly!

**Comment by paskino** [comment]
> Just tested and I found that: #22 was not fixed - when I created a pointcloud, the subvolume regions were shown, and the "Display subvolume regions" checkbox was unticked. I am getting this issue with tiff files: [vais-ral/CILViewer#310](https://github.com/vais-ral/CILViewer/issues/310) - seems to be a closed issue in the viewer - it was closed by this PR: [vais-ral/CILViewer#311](https://github.com/vais-ral/CILViewer/pull/311) what is happening here which is different?
> 
> Otherwise, I am happy with the changes to the way the bulk run works

Apparently this is due to having viewer 22.2.0 installed instead of 22.4.0

I added the hiding of the subvolume actor for point cloud creation as well now!

**Review by lauramurgatroyd — APPROVED** [review]

**Pull request merged**
