### PR TITLE
Box clipping actor

### LINKED ISSUE #77: With vtk9 the pointcloud outline doesn't display and nor does the image registration box

### PR DESCRIPTION
**Pull request by paskino**
closes #77 

After investigating in a minimal [example](https://github.com/vais-ral/CILViewer/blob/cube_source/Wrappers/Python/examples/cubesource_clip.py), I found a workaround to display the clipped poly data (cube). This workaround is necessary because there has been a change in the VTK behaviour with version >=9.1.

The change requires adding the following to the appropriate actor properties

```python
actor.GetProperty().SetRepresentationToWireframe()
actor.GetProperty().SetRenderLinesAsTubes(True)
```

### CODE REVIEW

**Comment by lauramurgatroyd** [comment]
Can this PR include an update to the recipe and the environment.yml files?
https://github.com/TomographicImaging/iDVC/blob/ee01a8464071cfac293d58eaf178f3b86dc31757/recipe/meta.yaml#L51
Or will this come in a later PR?

**Comment by paskino** [comment]
I just forgot to add meta.yaml to the commit. Done now.

**Comment by lauramurgatroyd** [comment]
Please also update the environment .yml files that are in the same folder as the meta.yml

**Comment by paskino** [comment]
I removed the restriction to VTK 8.1.2

**Review by lauramurgatroyd — APPROVED** [review]

**Pull request merged**
